# Generated by Django 3.1.3 on 2022-08-05 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColdStorage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coldstorage',
            old_name='Image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ColdStorage.userprofile'),
        ),
    ]
