# Generated by Django 3.1.3 on 2022-08-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColdStorage', '0002_auto_20220805_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='applyDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='fromDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='remarkDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='toDate',
            field=models.DateField(null=True),
        ),
    ]
