# Generated by Django 3.1.3 on 2022-08-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColdStorage', '0003_auto_20220806_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='applyDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='fromDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='remarkDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='toDate',
            field=models.DateTimeField(null=True),
        ),
    ]
